apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        # Image name will be dynamically updated by CI/CD pipeline
        image: flask-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: BUILD_VERSION
          value: "local"  # default value, overridden in CI/CD
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
