---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-demo
spec:
  type: NodePort
  selector:
    app: flask-demo
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
